final List<String> cardImages = [
  // 클럽 카드
  'assets/images/cards/club_2.png',
  'assets/images/cards/club_3.png',
  'assets/images/cards/club_4.png',
  'assets/images/cards/club_5.png',
  'assets/images/cards/club_6.png',
  'assets/images/cards/club_7.png',
  'assets/images/cards/club_8.png',
  'assets/images/cards/club_9.png',
  'assets/images/cards/club_10.png',
  'assets/images/cards/club_A.png',
  'assets/images/cards/club_K.png',
  'assets/images/cards/club_Q.png',
  'assets/images/cards/club_J.png',
  // 다이아몬드 카드
  'assets/images/cards/diamond_2.png',
  'assets/images/cards/diamond_3.png',
  'assets/images/cards/diamond_4.png',
  'assets/images/cards/diamond_5.png',
  'assets/images/cards/diamond_6.png',
  'assets/images/cards/diamond_7.png',
  'assets/images/cards/diamond_8.png',
  'assets/images/cards/diamond_9.png',
  'assets/images/cards/diamond_10.png',
  'assets/images/cards/diamond_A.png',
  'assets/images/cards/diamond_K.png',
  'assets/images/cards/diamond_Q.png',
  'assets/images/cards/diamond_J.png',
  // 하트 카드
  'assets/images/cards/heart_2.png',
  'assets/images/cards/heart_3.png',
  'assets/images/cards/heart_4.png',
  'assets/images/cards/heart_5.png',
  'assets/images/cards/heart_6.png',
  'assets/images/cards/heart_7.png',
  'assets/images/cards/heart_8.png',
  'assets/images/cards/heart_9.png',
  'assets/images/cards/heart_10.png',
  'assets/images/cards/heart_A.png',
  'assets/images/cards/heart_K.png',
  'assets/images/cards/heart_Q.png',
  'assets/images/cards/heart_J.png',
  // 스페이드 카드
  'assets/images/cards/spade_2.png',
  'assets/images/cards/spade_3.png',
  'assets/images/cards/spade_4.png',
  'assets/images/cards/spade_5.png',
  'assets/images/cards/spade_6.png',
  'assets/images/cards/spade_7.png',
  'assets/images/cards/spade_8.png',
  'assets/images/cards/spade_9.png',
  'assets/images/cards/spade_10.png',
  'assets/images/cards/spade_A.png',
  'assets/images/cards/spade_K.png',
  'assets/images/cards/spade_Q.png',
  'assets/images/cards/spade_J.png',
];
